in_channels: 1
out_channels: 1
down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
block_out_channels: [128, 256, 512, 512, 512]
layers_per_block: 2
latent_channels: 4
norm_num_groups: 32